const pokemon = [
  {
    name: "Bulbasaur",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Vine Whip", power: 45 },
    // { name: "Razor Leaf", power: 55 },
    // { name: "Solar Beam", power: 120 },
    move1: 32,
    move2: 21,
    move3: 73,
    move4: 74,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/001bulbasaur_buvbux.png",
    hp: 45,
  },
  {
    name: "Ivysaur",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Vine Whip", power: 45 },
    // { name: "Razor Leaf", power: 55 },
    // { name: "Solar Beam", power: 120 },
    move1: 32,
    move2: 21,
    move3: 73,
    move4: 74,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/002ivysaur_abqi3c.png",
    hp: 60,
  },
  {
    name: "Venusaur",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 3,
    // { name: "Tackle", power: 40 },
    // { name: "Vine Whip", power: 45 },
    // { name: "Razor Leaf", power: 55 },
    // { name: "Solar Beam", power: 120 },
    move1: 32,
    move2: 21,
    move3: 73,
    move4: 74,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/003venusaur_zkyiww.png",
    hp: 80,
  },
  {
    name: "Charmander",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Ember", power: 40 },
    // { name: "Flamethrower", power: 90 },
    // { name: "Fire Blast", power: 110 },
    move1: 10,
    move2: 50,
    move3: 51,
    move4: 126,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/004charmander_h67gmz.png",
    hp: 39,
  },
  {
    name: "Charmeleon",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 2,
    // { name: "Scratch", power: 40 },
    // { name: "Ember", power: 40 },
    // { name: "Flamethrower", power: 90 },
    // { name: "Fire Blast", power: 110 },
    move1: 10,
    move2: 50,
    move3: 51,
    move4: 126,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/005charmeleon_tg2h5v.png",
    hp: 58,
  },
  {
    name: "Charizard",
    type: "Fire",
    secondary_type: "Flying",
    weakness: "water",
    strength: "grass",
    tier: 3,
    // { name: "Scratch", power: 40 },
    // { name: "Ember", power: 40 },
    // { name: "Flamethrower", power: 90 },
    // { name: "Fire Blast", power: 110 },
    move1: 10,
    move2: 50,
    move3: 51,
    move4: 126,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/006charizard_oshtvp.png",
    hp: 78,
  },
  {
    name: "Squirtle",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Water Gun", power: 40 },
    // { name: "Bubble Beam", power: 65 },
    // { name: "Hydro Pump", power: 110 },
    move1: 32,
    move2: 53,
    move3: 59,
    move4: 54,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/007squirtle_rpx9yc.png",
    hp: 44,
  },
  {
    name: "Wartortle",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Water Gun", power: 40 },
    // { name: "Bubble Beam", power: 65 },
    // { name: "Hydro Pump", power: 110 },
    move1: 32,
    move2: 53,
    move3: 59,
    move4: 54,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/008wartortle_elkrpj.png",
    hp: 59,
  },
  {
    name: "Blastoise",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 3,
    // { name: "Water Gun", power: 40 },
    // { name: "Hydro Pump", power: 110 },
    // { name: "Skull Bash", power: 130 },
    // { name: "Ice Beam", power: 90 },
    move1: 32,
    move2: 53,
    move3: 59,
    move4: 54,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/009blastoise_q3jis6.png",
    hp: 79,
  },
  {
    name: "Caterpie",
    type: "Bug",
    secondary_type: null,
    weakness: "fire",
    strength: "grass",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Twineedle", power: 25 },
    // { name: "Quick Attack", power: 80 },
    move1: 32,
    move2: 39,
    move3: 40,
    move4: 389,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/010caterpie_hoxnoy.png",
    hp: 45,
  },
  {
    name: "Metapod",
    type: "Bug",
    secondary_type: null,
    weakness: "fire",
    strength: "grass",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Cut", power: 50 },
    // { name: "Twineedle", power: 25 },
    // { name: "Absorb", power: 20 },
    move1: 32,
    move2: 15,
    move3: 40,
    move4: 69,
    rarity: "common",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896179/011metapod_znlhgt.png",
    hp: 50,
  },
  {
    name: "Butterfree",
    type: "Bug",
    secondary_type: "Flying",
    weakness: "fire",
    strength: "grass",
    tier: 3,
    // { name: "Confusion", power: 50 },
    // { name: "Psybeam", power: 65 },
    // { name: "Razor Wind", power: 60 },
    // { name: "Solar Beam", power: 120 },
    move1: 388,
    move2: 58,
    move3: 13,
    move4: 74,
    rarity: "rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896180/012butterfree_ehxmmz.png",
    hp: 60,
  },
  {
    name: "Weedle",
    type: "Bug",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "grass",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Twineedle", power: 25 },
    // { name: "Quick Attack", power: 80 },
    move1: 32,
    move2: 39,
    move3: 40,
    move4: 389,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896180/013weedle_bjicdr.png",
    hp: 40,
  },
  {
    name: "Kakuna",
    type: "Bug",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "grass",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Twineedle", power: 25 },
    // { name: "Absorb", power: 20 },
    move1: 32,
    move2: 39,
    move3: 40,
    move4: 69,
    rarity: "common",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896180/014kakuna_fn0p9n.png",
    hp: 45,
  },
  {
    name: "Beedrill",
    type: "Bug",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "grass",
    tier: 2,
    // { name: "Bug Bite", power: 65 },
    // { name: "Twineedle", power: 25 },
    // { name: "Pin Missile", power: 25 },
    // { name: "Leech Life", power: 80 },
    move1: 84,
    move2: 40,
    move3: 83,
    move4: 101,
    rarity: "rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896180/015beedrill_oj8eye.png",
    hp: 65,
  },
  {
    name: "Pidgey",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "bug",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Gust", power: 40 },
    // { name: "Peck", power: 35 },
    // { name: "Drill Peck", power: 80 },
    move1: 32,
    move2: 16,
    move3: 62,
    move4: 63,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896180/016pidgey_dnc3a1.png",
    hp: 40,
  },
  {
    name: "Pidgeotto",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "bug",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Gust", power: 40 },
    // { name: "Fly", power: 90 },
    // { name: "Drill Peck", power: 80 },
    move1: 32,
    move2: 16,
    move3: 18,
    move4: 63,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896180/017pidgeotto_kurn9i.png",
    hp: 63,
  },
  {
    name: "Pidgeot",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "bug",
    tier: 3,
    // { name: "Gust", power: 40 },
    // { name: "Wing Attack", power: 60 },
    // { name: "Aerial Ace", power: 60 },
    // { name: "Sky Attack", power: 110 },
    move1: 16,
    move2: 17,
    move3: 390,
    move4: 143,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896180/018pidgeot_vrgb5y.png",
    hp: 83,
  },
  {
    name: "Rattata",
    type: "Normal",
    secondary_type: "Dark",
    weakness: "fighting",
    strength: "ghost",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Quick Attack", power: 40 },
    // { name: "Hyper Fang", power: 80 },
    // { name: "Scratch", power: 40 },
    move1: 32,
    move2: 389,
    move3: 158,
    move4: 10,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/019rattata_murak1.png",
    hp: 30,
  },
  {
    name: "Raticate",
    type: "Normal",
    secondary_type: "Dark",
    weakness: "fighting",
    strength: "ghost",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Quick Attack", power: 40 },
    // { name: "Hyper Fang", power: 80 },
    // { name: "Headbutt", power: 70 },
    move1: 32,
    move2: 389,
    move3: 158,
    move4: 28,
    rarity: "common",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/020raticate_p3udbn.png",
    hp: 32,
  },
  {
    name: "Spearow",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "electic",
    strength: "bug",
    tier: 1,
    // { name: "Peck", power: 35 },
    // { name: "Drill Peck", power: 80 },
    // { name: "Gust", power: 40 },
    // { name: "Aerial Ace", power: 60 },
    move1: 62,
    move2: 63,
    move3: 16,
    move4: 390,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/021spearow_oyyn65.png",
    hp: 40,
  },
  {
    name: "Fearow",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "electic",
    strength: "bug",
    tier: 2,
    // { name: "Peck", power: 35 },
    // { name: "Drill Peck", power: 80 },
    // { name: "Sky Attack", power: 140 },
    // { name: "Aerial Ace", power: 60 },
    move1: 62,
    move2: 63,
    move3: 143,
    move4: 390,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/022fearow_gulf9l.png",
    hp: 65,
  },
  {
    name: "Ekans",
    type: "Poison",
    secondary_type: null,
    weakness: "ground",
    strength: "fairy",
    tier: 1,
    // { name: "Wrap", power: 15 },
    // { name: "Bite", power: 60 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Acid", power: 40 },
    move1: 34,
    move2: 4,
    move3: 39,
    move4: 49,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896182/023ekans_aoinvc.png",
    hp: 35,
  },
  {
    name: "Arbok",
    type: "Poison",
    secondary_type: null,
    weakness: "ground",
    strength: "fairy",
    tier: 2,
    // { name: "Wrap", power: 15 },
    // { name: "Bite", power: 60 },
    // { name: "Hyper Fang", power: 80 },
    // { name: "Acid", power: 40 },
    move1: 34,
    move2: 4,
    move3: 158,
    move4: 49,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/024arbok_pouikt.png",
    hp: 60,
  },
  {
    name: "Pikachu",
    type: "Electric",
    secondary_type: null,
    weakness: "rock",
    strength: "flying",
    tier: 1,
    // { name: "Quick Attack", power: 40 },
    // { name: "Thunder Shock", power: 40 },
    // { name: "Tackle", power: 60 },
    // { name: "Thunderbolt", power: 90 },
    move1: 389,
    move2: 391,
    move3: 32,
    move4: 243,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/025pikachu_q66dwq.png",
    hp: 35,
  },
  {
    name: "Raichu",
    type: "Electric",
    secondary_type: null,
    weakness: "rock",
    strength: "flying",
    tier: 2,
    // { name: "Quick Attack", power: 40 },
    // { name: "Thunder Shock", power: 40 },
    // { name: "Thunder Punch", power: 75 },
    // { name: "Thunder", power: 110 },
    move1: 389,
    move2: 391,
    move3: 9,
    move4: 252,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/026raichu_oi2nci.png",
    hp: 60,
  },
  {
    name: "Sandshrew",
    type: "Ground",
    secondary_type: null,
    weakness: "fighting",
    strength: "poison",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Slash", power: 70 },
    // { name: "Earthquake", power: 100 },
    move1: 10,
    move2: 39,
    move3: 163,
    move4: 280,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896181/027sandshrew_xpsxma.png",
    hp: 50,
  },
  {
    name: "Sandslash",
    type: "Ground",
    secondary_type: null,
    weakness: "fighting",
    strength: "poison",
    tier: 2,
    // { name: "Headbutt", power: 70 },
    // { name: "Dig", power: 80 },
    // { name: "Slash", power: 70 },
    // { name: "Earthquake", power: 100 },
    move1: 28,
    move2: 392,
    move3: 163,
    move4: 280,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896182/028sandslash_dqtrix.png",
    hp: 75,
  },
  {
    name: "Nidoran♀",
    type: "Poison",
    secondary_type: null,
    weakness: "ground",
    strength: "fairy",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Bite", power: 60 },
    // { name: "Sludge", power: 65 },
    move1: 10,
    move2: 39,
    move3: 42,
    move4: 124,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896182/029nidoran_bo6c22.png",
    hp: 32,
  },
  {
    name: "Nidorina",
    type: "Poison",
    secondary_type: null,
    weakness: "ground",
    strength: "fairy",
    tier: 2,
    // { name: "Scratch", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Bite", power: 60 },
    // { name: "Thrash", power: 120 },
    move1: 10,
    move2: 39,
    move3: 42,
    move4: 36,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896182/030nidorina_zxvqta.png",
    hp: 70,
  },
  {
    name: "Nidoqueen",
    type: "Poison",
    secondary_type: "Ground",
    weakness: "ground",
    strength: "fairy",
    tier: 3,
    // { name: "Body Slam", power: 85 },
    // { name: "Earthquake", power: 100 },
    // { name: "Horn Attack", power: 65 },
    // { name: "Skull Bash", power: 130 },
    move1: 33,
    move2: 280,
    move3: 29,
    move4: 130,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896182/031nidoqueen_iyzwmv.png",
    hp: 90,
  },
  {
    name: "Nidoran♂",
    type: "Poison",
    secondary_type: null,
    weakness: "ground",
    strength: "fairy",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Bite", power: 60 },
    // { name: "Sludge", power: 65 },
    move1: 10,
    move2: 39,
    move3: 42,
    move4: 124,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896182/032nidoran_yw0phh.png",
    hp: 46,
  },
  {
    name: "Nidorino",
    type: "Poison",
    secondary_type: null,
    weakness: "ground",
    strength: "fairy",
    tier: 2,
    // { name: "Scratch", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Bite", power: 60 },
    // { name: "Thrash", power: 120 },
    move1: 10,
    move2: 39,
    move3: 42,
    move4: 36,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896182/033nidorino_kc4ae3.png",
    hp: 61,
  },
  {
    name: "Nidoking",
    type: "Poison",
    secondary_type: "Ground",
    weakness: "ground",
    strength: "fairy",
    tier: 3,
    // { name: "Thrash", power: 120 },
    // { name: "Earthquake", power: 100 },
    // { name: "Horn Attack", power: 65 },
    // { name: "Skull Bash", power: 130 },
    move1: 33,
    move2: 280,
    move3: 29,
    move4: 130,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896183/034nidoking_qrecwj.png",
    hp: 81,
  },
  {
    name: "Clefairy",
    type: "Fairy",
    secondary_type: null,
    weakness: "poison",
    strength: "fighting",
    tier: 1,
    // { name: "Pound", power: 40 },
    // { name: "Play Rough", power: 90 },
    // { name: "Lovely Kiss", power: 50 },
    // { name: "Moonblast", power: 95 },
    move1: 1,
    move2: 198,
    move3: 142,
    move4: 220,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896183/035clefairy_veeacy.png",
    hp: 70,
  },
  {
    name: "Clefable",
    type: "Fairy",
    secondary_type: null,
    weakness: "poison",
    strength: "fighting",
    tier: 3,
    // { name: "Double Slap", power: 15 },
    // { name: "Moonblast", power: 95 },
    // { name: "Disarming Voice", power: 40 },
    // { name: "Seismic Toss", power: 90 },
    move1: 3,
    move2: 220,
    move3: 394,
    move4: 67,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896183/036clefable_c2ekjd.png",
    hp: 95,
  },
  {
    name: "Vulpix",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 1,
    // { name: "Ember", power: 40 },
    // { name: "Quick Attack", power: 40 },
    // { name: "Flamethrower", power: 90 },
    // { name: "Fire Spin", power: 35 },
    move1: 50,
    move2: 389,
    move3: 51,
    move4: 395,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896183/037vulpix_odwnss.png",
    hp: 38,
  },
  {
    name: "Ninetales",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 3,
    // { name: "Fire Spin", power: 35 },
    // { name: "Quick Attack", power: 40 },
    // { name: "Flamethrower", power: 90 },
    // { name: "Solar Beam", power: 120 },
    move1: 395,
    move2: 389,
    move3: 51,
    move4: 74,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896183/038ninetales_nawnyy.png",
    hp: 73,
  },
  {
    name: "Jigglypuff",
    type: "Fairy",
    secondary_type: "Normal",
    weakness: "ghost",
    strength: "fighting",
    tier: 1,
    // { name: "Pound", power: 40 },
    // { name: "Disarming Voice", power: 40 },
    // { name: "Double Slap", power: 15 },
    // { name: "Play Rough", power: 90 },
    move1: 1,
    move2: 394,
    move3: 3,
    move4: 198,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896183/039jigglypuff_ycippk.png",
    hp: 115,
  },
  {
    name: "Wigglytuff",
    type: "Fairy",
    secondary_type: "Normal",
    weakness: "ghost",
    strength: "fighting",
    tier: 3,
    // { name: "Pound", power: 40 },
    // { name: "Play Rough", power: 90 },
    // { name: "Hyper Voice", power: 90 },
    // { name: "Dazzling Gleam", power: 80 },
    move1: 1,
    move2: 198,
    move3: 209,
    move4: 308,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896184/040wigglytuff_yas06i.png",
    hp: 140,
  },
  {
    name: "Zubat",
    type: "Poison",
    secondary_type: "Flying",
    weakness: "rock",
    strength: "ground",
    tier: 1,
    // { name: "Leech Life", power: 80 },
    // { name: "Wing Attack", power: 60 },
    // { name: "Air Cutter", power: 60 },
    // { name: "Poison Fang", power: 50 },
    move1: 101,
    move2: 89,
    move3: 207,
    move4: 396,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896184/041zubat_rodkvz.png",
    hp: 40,
  },
  {
    name: "Golbat",
    type: "Poison",
    secondary_type: "Flying",
    weakness: "rock",
    strength: "ground",
    tier: 2,
    // { name: "Wing Attack", power: 60 },
    // { name: "Air Cutter", power: 60 },
    // { name: "Poison Fang", power: 50 },
    // { name: "Brave Bird", power: 120 },
    move1: 17,
    move2: 207,
    move3: 396,
    move4: 370,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896184/042golbat_zswxfg.png",
    hp: 75,
  },
  {
    name: "Oddish",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 1,
    // { name: "Absorb", power: 20 },
    // { name: "Acid", power: 40 },
    // { name: "Giga Drain", power: 75 },
    // { name: "Moonblast", power: 95 },
    move1: 69,
    move2: 49,
    move3: 397,
    move4: 220,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896184/043oddish_xsl2aw.png",
    hp: 45,
  },
  {
    name: "Gloom",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 2,
    // { name: "Absorb", power: 20 },
    // { name: "Acid", power: 40 },
    // { name: "Petal Dance", power: 120 },
    // { name: "Sludge Bomb", power: 90 },
    move1: 69,
    move2: 49,
    move3: 78,
    move4: 398,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896184/044gloom_wa5bdg.png",
    hp: 60,
  },
  {
    name: "Vileplume",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 3,
    // { name: "Petal Dance", power: 120 },
    // { name: "Solar Beam", power: 120 },
    // { name: "Moonblast", power: 95 },
    // { name: "Sludge Bomb", power: 90 },
    move1: 78,
    move2: 74,
    move3: 220,
    move4: 398,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896184/045vileplume_wrlvxl.png",
    hp: 75,
  },
  {
    name: "Paras",
    type: "Bug",
    secondary_type: "Grass",
    weakness: "fire",
    strength: "water",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Slash", power: 70 },
    // { name: "Leech Life", power: 80 },
    // { name: "Seed Bomb", power: 80 },
    move1: 10,
    move2: 163,
    move3: 101,
    move4: 271,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896185/046paras_mffg7w.png",
    hp: 35,
  },
  {
    name: "Parasect",
    type: "Bug",
    secondary_type: "Grass",
    weakness: "fire",
    strength: "water",
    tier: 2,
    // { name: "Fury Cutter", power: 40 },
    // { name: "Cross Poison", power: 70 },
    // { name: "Leech Life", power: 80 },
    // { name: "Solar Beam", power: 120 },
    move1: 282,
    move2: 399,
    move3: 101,
    move4: 74,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896185/047parasect_she7i4.png",
    hp: 60,
  },
  {
    name: "Venonat",
    type: "Bug",
    secondary_type: "Poison",
    weakness: "flying",
    strength: "grass",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Psybeam", power: 65 },
    // { name: "Signal Beam", power: 75 },
    move1: 32,
    move2: 388,
    move3: 58,
    move4: 291,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896185/048venonat_sl224y.png",
    hp: 60,
  },
  {
    name: "Venomoth",
    type: "Bug",
    secondary_type: "Poison",
    weakness: "flying",
    strength: "grass",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Psybeam", power: 65 },
    // { name: "Leech Life", power: 80 },
    move1: 32,
    move2: 388,
    move3: 58,
    move4: 101,
    rarity: "very rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896185/049venomoth_trlfd0.png",
    hp: 70,
  },
  {
    name: "Diglett",
    type: "Ground",
    secondary_type: null,
    weakness: "fighting",
    strength: "poison",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Mud Slap", power: 20 },
    // { name: "Magnitude", power: 70 },
    // { name: "Earthquake", power: 100 },
    move1: 10,
    move2: 400,
    move3: 401,
    move4: 280,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896185/050diglett_mwvsmd.png",
    hp: 10,
  },
  {
    name: "Dugtrio",
    type: "Ground",
    secondary_type: null,
    weakness: "fighting",
    strength: "poison",
    tier: 3,
    // { name: "Slash", power: 70 },
    // { name: "Earth Power", power: 90 },
    // { name: "Earthquake", power: 100 },
    // { name: "Stone Edge", power: 100 },
    move1: 163,
    move2: 327,
    move3: 280,
    move4: 189,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896185/051dugtrio_cl3zuz.png",
    hp: 35,
  },
  {
    name: "Meowth",
    type: "Normal",
    secondary_type: null,
    weakness: "dark",
    strength: "ghost",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Bite", power: 60 },
    // { name: "Pay Day", power: 40 },
    // { name: "Feint Attack", power: 60 },
    move1: 10,
    move2: 42,
    move3: 6,
    move4: 226,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/052meowth_tqld32.png",
    hp: 40,
  },
  {
    name: "Persian",
    type: "Normal",
    secondary_type: null,
    weakness: "dark",
    strength: "ghost",
    tier: 2,
    // { name: "Scratch", power: 40 },
    // { name: "Bite", power: 60 },
    // { name: "Slash", power: 70 },
    // { name: "Hyper Beam", power: 150 },
    move1: 10,
    move2: 42,
    move3: 163,
    move4: 61,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/053persian_xgbopz.png",
    hp: 65,
  },
  //
  //
  //
  //
  //
  //
  //
  //
  {
    name: "Psyduck",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Water Gun", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Hydro Pump", power: 110 },
    move1: 10,
    move2: 53,
    move3: 388,
    move4: 54,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/054psyduck_s5pwcu.png",
    hp: 50,
  },
  {
    name: "Golduck",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Water Gun", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Hydro Pump", power: 110 },
    // { name: "Ice Beam", power: 90 },
    move1: 53,
    move2: 388,
    move3: 54,
    move4: 56,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/055golduck_xfa34l.png",
    hp: 80,
  },
  {
    name: "Mankey",
    type: "Fighting",
    secondary_type: null,
    weakness: "ghost",
    strength: "ground",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Low Kick", power: 50 },
    // { name: "Karate Chop", power: 50 },
    // { name: "Cross Chop", power: 100 },
    move1: 10,
    move2: 65,
    move3: 2,
    move4: 303,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/056mankey_kxpjlc.png",
    hp: 40,
  },
  {
    name: "Primeape",
    type: "Fighting",
    secondary_type: null,
    weakness: "ghost",
    strength: "ground",
    tier: 2,
    // { name: "Karate Chop", power: 50 },
    // { name: "Cross Chop", power: 100 },
    // { name: "Low Kick", power: 50 },
    // { name: "Close Combat", power: 120 },
    move1: 2,
    move2: 303,
    move3: 65,
    move4: 199,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/057primeape_vniids.png",
    hp: 65,
  },
  {
    name: "Growlithe",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 1,
    // { name: "Bite", power: 60 },
    // { name: "Ember", power: 40 },
    // { name: "Flame Wheel", power: 60 },
    // { name: "Fire Blast", power: 110 },
    move1: 42,
    move2: 50,
    move3: 172,
    move4: 126,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/058growlithe_ajrmg5.png",
    hp: 32,
  },
  {
    name: "Arcanine",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 3,
    // { name: "Bite", power: 60 },
    // { name: "Flamethrower", power: 90 },
    // { name: "Extreme Speed", power: 80 },
    // { name: "Fire Blast", power: 110 },
    move1: 42,
    move2: 248,
    move3: 402,
    move4: 126,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896186/059arcanine_p24is4.png",
    hp: 90,
  },
  {
    name: "Poliwag",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Bubble", power: 40 },
    // { name: "Water Gun", power: 40 },
    // { name: "Body Slam", power: 85 },
    // { name: "Bubble Beam", power: 65 },
    move1: 145,
    move2: 53,
    move3: 33,
    move4: 59,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/060poliwag_qxbnfo.png",
    hp: 40,
  },
  {
    name: "Poliwhirl",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Water Gun", power: 40 },
    // { name: "Bubble Beam", power: 65 },
    // { name: "Ice Punch", power: 75 },
    // { name: "Hydro Pump", power: 110 },
    move1: 53,
    move2: 59,
    move3: 8,
    move4: 54,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/061poliwhirl_apqrrj.png",
    hp: 65,
  },
  {
    name: "Poliwrath",
    type: "Water",
    secondary_type: "Fighting",
    weakness: "electric",
    strength: "rock",
    tier: 3,
    // { name: "Bubble Beam", power: 65 },
    // { name: "Ice Punch", power: 75 },
    // { name: "Brick Break", power: 75 },
    // { name: "Hydro Pump", power: 110 },
    move1: 59,
    move2: 8,
    move3: 403,
    move4: 54,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/062poliwrath_j5i0cp.png",
    hp: 90,
  },
  {
    name: "Abra",
    type: "Psychic",
    secondary_type: null,
    weakness: "normal",
    strength: "ghost",
    tier: 2,
    // { name: "Pound", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Psybeam", power: 65 },
    // { name: "Shadow Ball", power: 80 },
    move1: 1,
    move2: 388,
    move3: 58,
    move4: 292,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/063abra_ntkn7l.png",
    hp: 25,
  },
  {
    name: "Kadabra",
    type: "Psychic",
    secondary_type: null,
    weakness: "normal",
    strength: "ghost",
    tier: 2,
    // { name: "Psybeam", power: 65 },
    // { name: "Confusion", power: 50 },
    // { name: "Shadow Ball", power: 80 },
    // { name: "Psychic", power: 90 },
    move1: 58,
    move2: 388,
    move3: 292,
    move4: 211,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/064kadabra_ccz8qo.png",
    hp: 40,
  },
  {
    name: "Alakazam",
    type: "Psychic",
    secondary_type: null,
    weakness: "normal",
    strength: "ghost",
    tier: 3,
    // { name: "Psybeam", power: 65 },
    // { name: "Psychic", power: 90 },
    // { name: "Shadow Ball", power: 80 },
    // { name: "Focus Blast", power: 120 },
    move1: 58,
    move2: 211,
    move3: 292,
    move4: 368,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/065alakazam_odb9na.png",
    hp: 32,
  },
  {
    name: "Machop",
    type: "Fighting",
    secondary_type: null,
    weakness: "ghost",
    strength: "ground",
    tier: 1,
    // { name: "Low Kick", power: 50 },
    // { name: "Karate Chop", power: 50 },
    // { name: "Low Sweep", power: 65 },
    // { name: "Dynamic Punch", power: 100 },
    move1: 65,
    move2: 2,
    move3: 232,
    move4: 404,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/066machop_rsrysv.png",
    hp: 70,
  },
  {
    name: "Machoke",
    type: "Fighting",
    secondary_type: null,
    weakness: "ghost",
    strength: "ground",
    tier: 2,
    // { name: "Karate Chop", power: 50 },
    // { name: "Low Sweep", power: 65 },
    // { name: "Cross Chop", power: 100 },
    // { name: "Submission", power: 80 },
    move1: 2,
    move2: 232,
    move3: 303,
    move4: 64,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/067machoke_kyeyxc.png",
    hp: 80,
  },
  {
    name: "Machamp",
    type: "Fighting",
    secondary_type: null,
    weakness: "ghost",
    strength: "ground",
    tier: 3,
    // { name: "Karate Chop", power: 50 },
    // { name: "Cross Chop", power: 100 },
    // { name: "Dynamic Punch", power: 100 },
    // { name: "Stone Edge", power: 100 },
    move1: 2,
    move2: 303,
    move3: 404,
    move4: 189,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/068machamp_hi5tpy.png",
    hp: 90,
  },
  {
    name: "Bellsprout",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 1,
    // { name: "Vine Whip", power: 45 },
    // { name: "Acid", power: 40 },
    // { name: "Razor Leaf", power: 55 },
    // { name: "Sludge Bomb", power: 90 },
    move1: 21,
    move2: 49,
    move3: 73,
    move4: 398,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/069bellsprout_l7gkvt.png",
    hp: 50,
  },
  {
    name: "Weepinbell",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 2,
    // { name: "Razor Leaf", power: 55 },
    // { name: "Sludge Bomb", power: 90 },
    // { name: "Seed Bomb", power: 80 },
    // { name: "Power Whip", power: 120 },
    move1: 73,
    move2: 398,
    move3: 271,
    move4: 405,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896187/070weepinbell_ah69mp.png",
    hp: 65,
  },
  {
    name: "Victreebel",
    type: "Grass",
    secondary_type: "Poison",
    weakness: "fire",
    strength: "water",
    tier: 3,
    // { name: "Leaf Blade", power: 90 },
    // { name: "Sludge Bomb", power: 90 },
    // { name: "Solar Beam", power: 120 },
    // { name: "Acid Spray", power: 40 },
    move1: 184,
    move2: 398,
    move3: 74,
    move4: 406,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/071victreebel_edpn4l.png",
    hp: 80,
  },
  {
    name: "Tentacool",
    type: "Water",
    secondary_type: "Poison",
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Poison Sting", power: 15 },
    // { name: "Bubble Beam", power: 65 },
    // { name: "Wrap", power: 15 },
    // { name: "Hydro Pump", power: 110 },
    move1: 39,
    move2: 59,
    move3: 34,
    move4: 54,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/072tentacool_pmrxpg.png",
    hp: 40,
  },
  {
    name: "Tentacruel",
    type: "Water",
    secondary_type: "Poison",
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Acid", power: 40 },
    // { name: "Hydro Pump", power: 110 },
    // { name: "Sludge Bomb", power: 90 },
    // { name: "Blizzard", power: 110 },
    move1: 49,
    move2: 54,
    move3: 398,
    move4: 57,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/073tentacruel_vgmn4z.png",
    hp: 80,
  },
  {
    name: "Geodude",
    type: "Rock",
    secondary_type: "Ground",
    weakness: "water",
    strength: "electric",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Rock Throw", power: 50 },
    // { name: "Magnitude", power: 70 },
    // { name: "Rock Slide", power: 75 },
    move1: 32,
    move2: 407,
    move3: 401,
    move4: 157,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/074geodude_qmwjbw.png",
    hp: 40,
  },
  {
    name: "Graveler",
    type: "Rock",
    secondary_type: "Ground",
    weakness: "water",
    strength: "electric",
    tier: 2,
    // { name: "Rock Throw", power: 50 },
    // { name: "Magnitude", power: 70 },
    // { name: "Rock Slide", power: 75 },
    // { name: "Earthquake", power: 100 },
    move1: 407,
    move2: 401,
    move3: 157,
    move4: 280,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896188/075graveler_lmzxsk.png",
    hp: 32,
  },
  {
    name: "Golem",
    type: "Rock",
    secondary_type: "Ground",
    weakness: "water",
    strength: "electric",
    tier: 3,
    // { name: "Rock Throw", power: 50 },
    // { name: "Earthquake", power: 100 },
    // { name: "Rock Slide", power: 75 },
    // { name: "Stone Edge", power: 100 },
    move1: 407,
    move2: 280,
    move3: 157,
    move4: 189,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/076golem_musf2s.png",
    hp: 80,
  },
  {
    name: "Ponyta",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "bug",
    tier: 1,
    // { name: "Ember", power: 40 },
    // { name: "Stomp", power: 65 },
    // { name: "Fire Spin", power: 35 },
    // { name: "Flame Wheel", power: 60 },
    move1: 50,
    move2: 22,
    move3: 395,
    move4: 172,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/077ponyta_zrwt7b.png",
    hp: 50,
  },
  {
    name: "Rapidash",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "bug",
    tier: 3,
    // { name: "Ember", power: 40 },
    // { name: "Fire Spin", power: 35 },
    // { name: "Stomp", power: 65 },
    // { name: "Fire Blast", power: 110 },
    move1: 50,
    move2: 395,
    move3: 22,
    move4: 126,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/078rapidash_qmcy2n.png",
    hp: 65,
  },
  {
    name: "Slowpoke",
    type: "Psychic",
    secondary_type: "Water",
    weakness: "electric",
    strength: "grass",
    tier: 1,
    // { name: "Water Gun", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Headbutt", power: 70 },
    // { name: "Psychic", power: 90 },
    move1: 53,
    move2: 388,
    move3: 28,
    move4: 211,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/079slowpoke_rlykll.png",
    hp: 90,
  },
  {
    name: "Slowbro",
    type: "Psychic",
    secondary_type: "Water",
    weakness: "electric",
    strength: "grass",
    tier: 3,
    // { name: "Water Gun", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Psychic", power: 90 },
    // { name: "Ice Beam", power: 90 },
    move1: 53,
    move2: 388,
    move3: 211,
    move4: 56,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/080slowbro_et5vqg.png",
    hp: 95,
  },
  {
    name: "Magnemite",
    type: "Electric",
    secondary_type: "Steel",
    weakness: "rock",
    strength: "flying",
    tier: 1,
    // { name: "Thunder Shock", power: 40 },
    // { name: "Spark", power: 65 },
    // { name: "Thunderbolt", power: 90 },
    // { name: "Flash Cannon", power: 80 },
    move1: 391,
    move2: 407,
    move3: 243,
    move4: 215,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/081magnemite_s7nep7.png",
    hp: 25,
  },
  {
    name: "Magneton",
    type: "Electric",
    secondary_type: "Steel",
    weakness: "rock",
    strength: "flying",
    tier: 3,
    // { name: "Spark", power: 65 },
    // { name: "Thunderbolt", power: 90 },
    // { name: "Flash Cannon", power: 80 },
    // { name: "Zap Cannon", power: 120 },
    move1: 407,
    move2: 243,
    move3: 215,
    move4: 188,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/082magneton_brbl3f.png",
    hp: 50,
  },
  {
    name: "Farfetch'd",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "dark",
    strength: "fire",
    tier: 2,
    // { name: "Peck", power: 35 },
    // { name: "Fury Attack", power: 45 },
    // { name: "Air Slash", power: 75 },
    // { name: "Brave Bird", power: 120 },
    move1: 62,
    move2: 30,
    move3: 298,
    move4: 370,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/083farfetchd_dzp5rq.png",
    hp: 52,
  },
  {
    name: "Doduo",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "ground",
    tier: 1,
    // { name: "Peck", power: 35 },
    // { name: "Drill Peck", power: 80 },
    // { name: "Quick Attack", power: 40 },
    // { name: "Brave Bird", power: 120 },
    move1: 62,
    move2: 63,
    move3: 389,
    move4: 370,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/084doduo_sxvkcu.png",
    hp: 35,
  },
  {
    name: "Dodrio",
    type: "Normal",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "ground",
    tier: 2,
    // { name: "Drill Peck", power: 80 },
    // { name: "Tri Attack", power: 80 },
    // { name: "Jump Kick", power: 100 },
    // { name: "Brave Bird", power: 120 },
    move1: 63,
    move2: 161,
    move3: 25,
    move4: 370,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/085dodrio_srjeqx.png",
    hp: 60,
  },
  {
    name: "Seel",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "grass",
    tier: 1,
    // { name: "Headbutt", power: 70 },
    // { name: "Aqua Jet", power: 40 },
    // { name: "Ice Beam", power: 90 },
    // { name: "Aurora Beam", power: 65 },
    move1: 28,
    move2: 194,
    move3: 56,
    move4: 60,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896189/086seel_phja05.png",
    hp: 65,
  },
  {
    name: "Dewgong",
    type: "Ice",
    secondary_type: "Water",
    weakness: "electric",
    strength: "grass",
    tier: 2,
    // { name: "Aqua Jet", power: 40 },
    // { name: "Ice Beam", power: 90 },
    // { name: "Aurora Beam", power: 65 },
    // { name: "Blizzard", power: 110 },
    move1: 194,
    move2: 56,
    move3: 60,
    move4: 57,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/087dewgong_i8r0cv.png",
    hp: 90,
  },
  {
    name: "Grimer",
    type: "Poison",
    secondary_type: "Dark",
    weakness: "ground",
    strength: "normal",
    tier: 1,
    // { name: "Pound", power: 40 },
    // { name: "Sludge", power: 65 },
    // { name: "Mud Bomb", power: 65 },
    // { name: "Gunk Shot", power: 120 },
    move1: 1,
    move2: 124,
    move3: 408,
    move4: 409,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/088grimer_ohtu44.png",
    hp: 80,
  },
  {
    name: "Muk",
    type: "Poison",
    secondary_type: "Dark",
    weakness: "ground",
    strength: "normal",
    tier: 2,
    // { name: "Sludge", power: 65 },
    // { name: "Mud Bomb", power: 65 },
    // { name: "Gunk Shot", power: 120 },
    // { name: "Dark Pulse", power: 80 },
    move1: 124,
    move2: 408,
    move3: 409,
    move4: 212,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/089muk_pnaen7.png",
    hp: 105,
  },
  {
    name: "Shellder",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "fire",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Ice Shard", power: 40 },
    // { name: "Water Pulse", power: 60 },
    // { name: "Icicle Spear", power: 25 },
    move1: 32,
    move2: 381,
    move3: 261,
    move4: 410,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/090shellder_gm735j.png",
    hp: 30,
  },
  {
    name: "Cloyster",
    type: "Ice",
    secondary_type: "Water",
    weakness: "electric",
    strength: "fire",
    tier: 2,
    // { name: "Ice Shard", power: 40 },
    // { name: "Aurora Beam", power: 65 },
    // { name: "Icicle Spear", power: 25 },
    // { name: "Hydro Pump", power: 110 },
    move1: 381,
    move2: 60,
    move3: 410,
    move4: 54,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/091cloyster_borxbq.png",
    hp: 50,
  },
  {
    name: "Gastly",
    type: "Ghost",
    secondary_type: "Poison",
    weakness: "fighting",
    strength: "fairy",
    tier: 2,
    // { name: "Lick", power: 30 },
    // { name: "Shadow Punch", power: 60 },
    // { name: "Sludge Bomb", power: 90 },
    // { name: "Dark Pulse", power: 80 },
    move1: 122,
    move2: 304,
    move3: 398,
    move4: 212,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/092gastly_dydqxr.png",
    hp: 30,
  },
  {
    name: "Haunter",
    type: "Ghost",
    secondary_type: "Poison",
    weakness: "fighting",
    strength: "fairy",
    tier: 3,
    // { name: "Shadow Punch", power: 60 },
    // { name: "Shadow Ball", power: 80 },
    // { name: "Sludge Bomb", power: 90 },
    // { name: "Dark Pulse", power: 80 },
    move1: 304,
    move2: 292,
    move3: 398,
    move4: 212,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/093haunter_xp0oie.png",
    hp: 45,
  },
  {
    name: "Gengar",
    type: "Ghost",
    secondary_type: "Poison",
    weakness: "fighting",
    strength: "fairy",
    tier: 3,
    // { name: "Shadow Claw", power: 70 },
    // { name: "Shadow Ball", power: 80 },
    // { name: "Sludge Bomb", power: 90 },
    // { name: "Focus Blast", power: 120 },
    move1: 192,
    move2: 292,
    move3: 398,
    move4: 398,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896190/094gengar_eqqs0x.png",
    hp: 60,
  },
  {
    name: "Onix",
    type: "Rock",
    secondary_type: "Ground",
    weakness: "water",
    strength: "electric",
    tier: 2,
    // { name: "Rock Throw", power: 50 },
    // { name: "Iron Tail", power: 100 },
    // { name: "Rock Slide", power: 75 },
    // { name: "Stone Edge", power: 100 },
    move1: 407,
    move2: 300,
    move3: 157,
    move4: 189,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/095onix_pprb9h.png",
    hp: 35,
  },
  {
    name: "Drowzee",
    type: "Psychic",
    secondary_type: null,
    weakness: "ghost",
    strength: "normal",
    tier: 1,
    // { name: "Pound", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Psybeam", power: 65 },
    // { name: "Psychic", power: 90 },
    move1: 1,
    move2: 388,
    move3: 58,
    move4: 211,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/096drowzee_cqpycs.png",
    hp: 60,
  },
  {
    name: "Hypno",
    type: "Psychic",
    secondary_type: null,
    weakness: "ghost",
    strength: "normal",
    tier: 3,
    // { name: "Pound", power: 40 },
    // { name: "Confusion", power: 50 },
    // { name: "Psybeam", power: 65 },
    // { name: "Psychic", power: 90 },
    move1: 1,
    move2: 388,
    move3: 58,
    move4: 211,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/097hypno_e34lmq.png",
    hp: 85,
  },
  {
    name: "Krabby",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Bubble", power: 40 },
    // { name: "Vice Grip", power: 55 },
    // { name: "Crabhammer", power: 100 },
    // { name: "Stomp", power: 65 },
    move1: 145,
    move2: 11,
    move3: 152,
    move4: 94,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/098krabby_uertei.png",
    hp: 30,
  },
  {
    name: "Kingler",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Bubble", power: 40 },
    // { name: "Vice Grip", power: 55 },
    // { name: "Crabhammer", power: 100 },
    // { name: "Guillotine", power: 0 },
    move1: 145,
    move2: 11,
    move3: 152,
    move4: 12,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/099kingler_t10ern.png",
    hp: 32,
  },
  {
    name: "Voltorb",
    type: "Electric",
    secondary_type: null,
    weakness: "rock",
    strength: "water",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Spark", power: 65 },
    // { name: "Swift", power: 60 },
    // { name: "Thunderbolt", power: 90 },
    move1: 32,
    move2: 407,
    move3: 129,
    move4: 243,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/100voltorb_wqm1xu.png",
    hp: 40,
  },
  {
    name: "Electrode",
    type: "Electric",
    secondary_type: null,
    weakness: "rock",
    strength: "water",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Swift", power: 60 },
    // { name: "Thunder", power: 110 },
    // { name: "Explosion", power: 250 },
    move1: 32,
    move2: 129,
    move3: 252,
    move4: 153,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/101electrode_mzyjlp.png",
    hp: 60,
  },
  {
    name: "Exeggcute",
    type: "Grass",
    secondary_type: "Psychic",
    weakness: "bug",
    strength: "water",
    tier: 1,
    // { name: "Barrage", power: 15 },
    // { name: "Hypnosis", power: 0 },
    // { name: "Leech Seed", power: 0 },
    // { name: "Solar Beam", power: 120 },
    move1: 140,
    move2: 121,
    move3: 71,
    move4: 74,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896191/102exeggcute_wbwlbc.png",
    hp: 60,
  },
  {
    name: "Exeggutor",
    type: "Grass",
    secondary_type: "Psychic",
    weakness: "bug",
    strength: "water",
    tier: 2,
    // { name: "Confusion", power: 50 },
    // { name: "Stomp", power: 65 },
    // { name: "Psychic", power: 90 },
    // { name: "Solar Beam", power: 120 },
    move1: 388,
    move2: 121,
    move3: 211,
    move4: 74,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896192/103exeggutor_t5m5kt.png",
    hp: 95,
  },
  {
    name: "Cubone",
    type: "Ground",
    secondary_type: null,
    weakness: "flying",
    strength: "bug",
    tier: 1,
    // { name: "Bone Club", power: 65 },
    // { name: "Headbutt", power: 70 },
    // { name: "Bonemerang", power: 50 },
    // { name: "Thrash", power: 120 },
    move1: 125,
    move2: 100,
    move3: 155,
    move4: 36,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896192/104cubone_gvgkq1.png",
    hp: 50,
  },
  {
    name: "Marowak",
    type: "Ground",
    secondary_type: null,
    weakness: "flying",
    strength: "bug",
    tier: 2,
    // { name: "Bone Club", power: 65 },
    // { name: "Headbutt", power: 70 },
    // { name: "Bonemerang", power: 50 },
    // { name: "Earthquake", power: 100 },
    move1: 125,
    move2: 100,
    move3: 155,
    move4: 280,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896192/105marowak_jafnpx.png",
    hp: 60,
  },
  {
    name: "Hitmonlee",
    type: "Fighting",
    secondary_type: null,
    weakness: "ghost",
    strength: "normal",
    tier: 3,
    // { name: "Brick Break", power: 75 },
    // { name: "Jump Kick", power: 100 },
    // { name: "Mega Kick", power: 120 },
    // { name: "High Jump Kick", power: 130 },
    move1: 403,
    move2: 97,
    move3: 96,
    move4: 136,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896192/106hitmonlee_hj37uk.png",
    hp: 50,
  },
  {
    name: "Hitmonchan",
    type: "Fighting",
    secondary_type: null,
    weakness: "ghost",
    strength: "normal",
    tier: 3,
    // { name: "Comet Punch", power: 18 },
    // { name: "Fire Punch", power: 75 },
    // { name: "Ice Punch", power: 75 },
    // { name: "Thunder Punch", power: 75 },
    move1: 4,
    move2: 7,
    move3: 8,
    move4: 9,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896192/107hitmonchan_s1upzu.png",
    hp: 50,
  },
  {
    name: "Lickitung",
    type: "Normal",
    secondary_type: null,
    weakness: "fighting",
    strength: "normal",
    tier: 1,
    // { name: "Lick", power: 30 },
    // { name: "Stomp", power: 65 },
    // { name: "Wrap", power: 15 },
    // { name: "Hyper Beam", power: 150 },
    move1: 122,
    move2: 94,
    move3: 34,
    move4: 61,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896192/108lickitung_mj2vvc.png",
    hp: 90,
  },
  {
    name: "Koffing",
    type: "Poison",
    secondary_type: null,
    weakness: "rock",
    strength: "normal",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Sludge", power: 65 },
    // { name: "Smog", power: 30 },
    // { name: "Self-Destruct", power: 100 },
    move1: 32,
    move2: 124,
    move3: 123,
    move4: 411,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896192/109koffing_i7yotl.png",
    hp: 40,
  },
  {
    name: "Weezing",
    type: "Poison",
    secondary_type: null,
    weakness: "rock",
    strength: "normal",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Sludge", power: 65 },
    // { name: "Smog", power: 30 },
    // { name: "Explosion", power: 250 },
    move1: 32,
    move2: 124,
    move3: 123,
    move4: 153,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/110weezing_nfjxlk.png",
    hp: 65,
  },
  {
    name: "Rhyhorn",
    type: "Ground",
    secondary_type: "Rock",
    weakness: "water",
    strength: "electric",
    tier: 2,
    // { name: "Horn Attack", power: 65 },
    // { name: "Stomp", power: 65 },
    // { name: "Rock Slide", power: 75 },
    // { name: "Earthquake", power: 100 },
    move1: 29,
    move2: 22,
    move3: 157,
    move4: 280,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/111rhyhorn_yi6s1w.png",
    hp: 80,
  },
  {
    name: "Rhydon",
    type: "Ground",
    secondary_type: "Rock",
    weakness: "water",
    strength: "electric",
    tier: 3,
    // { name: "Horn Attack", power: 65 },
    // { name: "Stomp", power: 65 },
    // { name: "Rock Slide", power: 75 },
    // { name: "Earthquake", power: 100 },
    move1: 29,
    move2: 22,
    move3: 157,
    move4: 280,
    rarity: "very rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/112rhydon_qag8rn.png",
    hp: 105,
  },
  {
    name: "Chansey",
    type: "Normal",
    secondary_type: null,
    weakness: "ghost",
    strength: "fighting",
    tier: 3,
    // { name: "Pound", power: 40 },
    // { name: "Egg Bomb", power: 100 },
    // { name: "Soft-Boiled", power: 0 },
    // { name: "Double-Edge", power: 120 },
    move1: 1,
    move2: 121,
    move3: 135,
    move4: 37,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/113chansey_faawf0.png",
    hp: 250,
  },
  {
    name: "Tangela",
    type: "Grass",
    secondary_type: null,
    weakness: "fire",
    strength: "water",
    tier: 1,
    // { name: "Constrict", power: 10 },
    // { name: "Vine Whip", power: 45 },
    // { name: "Slam", power: 80 },
    // { name: "Power Whip", power: 120 },
    move1: 132,
    move2: 21,
    move3: 20,
    move4: 405,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/114tangela_wplxop.png",
    hp: 65,
  },
  {
    name: "Kangaskhan",
    type: "Normal",
    secondary_type: null,
    weakness: "fighting",
    strength: "bug",
    tier: 2,
    // { name: "Comet Punch", power: 18 },
    // { name: "Bite", power: 60 },
    // { name: "Rage", power: 20 },
    // { name: "Dizzy Punch", power: 70 },
    move1: 4,
    move2: 42,
    move3: 412,
    move4: 146,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/115kangaskhan_jouywt.png",
    hp: 105,
  },
  {
    name: "Horsea",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Bubble", power: 40 },
    // { name: "Water Gun", power: 40 },
    // { name: "Bubble Beam", power: 65 },
    // { name: "Poison Sting", power: 15 },
    move1: 145,
    move2: 53,
    move3: 59,
    move4: 39,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/116horsea_vxowfy.png",
    hp: 30,
  },
  {
    name: "Seadra",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Water Gun", power: 40 },
    // { name: "Bubble Beam", power: 65 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Hydro Pump", power: 110 },
    move1: 53,
    move2: 59,
    move3: 39,
    move4: 54,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896194/117seadra_beicdl.png",
    hp: 32,
  },
  {
    name: "Goldeen",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Peck", power: 35 },
    // { name: "Horn Attack", power: 65 },
    // { name: "Fury Attack", power: 15 },
    // { name: "Waterfall", power: 80 },
    move1: 62,
    move2: 29,
    move3: 30,
    move4: 127,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896193/118goldeen_dcyhb0.png",
    hp: 45,
  },
  {
    name: "Seaking",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Peck", power: 35 },
    // { name: "Waterfall", power: 80 },
    // { name: "Horn Attack", power: 65 },
    // { name: "Surf", power: 90 },
    move1: 62,
    move2: 127,
    move3: 29,
    move4: 55,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896194/119seaking_doptqb.png",
    hp: 80,
  },
  {
    name: "Staryu",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Tackle", power: 40 },
    // { name: "Water Gun", power: 40 },
    // { name: "Swift", power: 60 },
    // { name: "Spike Cannon", power: 20 },
    move1: 32,
    move2: 53,
    move3: 129,
    move4: 131,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896194/120staryu_dmpnmi.png",
    hp: 30,
  },
  {
    name: "Starmie",
    type: "Psychic",
    secondary_type: "Water",
    weakness: "electric",
    strength: "rock",
    tier: 2,
    // { name: "Water Gun", power: 40 },
    // { name: "Swift", power: 60 },
    // { name: "Psychic", power: 90 },
    // { name: "Hydro Pump", power: 110 },
    move1: 53,
    move2: 129,
    move3: 211,
    move4: 54,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/121starmie_eoheez.png",
    hp: 60,
  },
  {
    name: "Mr. Mime",
    type: "Psychic",
    secondary_type: "Fairy",
    weakness: "ghost",
    strength: "normal",
    tier: 3,
    // { name: "Confusion", power: 50 },
    // { name: "Metranome", power: 60 },
    // { name: "Constrict", power: 10 },
    // { name: "Psychic", power: 90 },
    move1: 388,
    move2: 119,
    move3: 132,
    move4: 211,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/122mrmime_hvyxb2.png",
    hp: 40,
  },
  {
    name: "Scyther",
    type: "Bug",
    secondary_type: "Flying",
    weakness: "flying",
    strength: "grass",
    tier: 2,
    // { name: "Quick Attack", power: 40 },
    // { name: "Double Team", power: 0 },
    // { name: "Slash", power: 70 },
    // { name: "Swords Dance", power: 0 },
    move1: 389,
    move2: 105,
    move3: 163,
    move4: 14,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/123scyther_xmbhnn.png",
    hp: 70,
  },
  {
    name: "Jynx",
    type: "Psychic",
    secondary_type: null,
    weakness: "ghost",
    strength: "fairy",
    tier: 2,
    // { name: "Pound", power: 40 },
    // { name: "Ice Punch", power: 75 },
    // { name: "Lovely Kiss", power: 0 },
    // { name: "Blizzard", power: 110 },
    move1: 1,
    move2: 8,
    move3: 142,
    move4: 57,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/124jynx_lj8v9p.png",
    hp: 65,
  },
  {
    name: "Electabuzz",
    type: "Electric",
    secondary_type: null,
    weakness: "ground",
    strength: "flying",
    tier: 3,
    // { name: "Quick Attack", power: 40 },
    // { name: "Thunder Punch", power: 75 },
    // { name: "Volt Tackle", power: 120 },
    // { name: "Thunderbolt", power: 90 },
    move1: 389,
    move2: 9,
    move3: 182,
    move4: 243,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/125electabuzz_jfp7qa.png",
    hp: 65,
  },
  {
    name: "Magmar",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 3,
    // { name: "Ember", power: 40 },
    // { name: "Fire Punch", power: 75 },
    // { name: "Fire Spin", power: 35 },
    // { name: "Flamethrower", power: 90 },
    move1: 50,
    move2: 7,
    move3: 395,
    move4: 51,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/126magmar_ltw1l2.png",
    hp: 65,
  },
  {
    name: "Pinsir",
    type: "Bug",
    secondary_type: null,
    weakness: "normal",
    strength: "grass",
    tier: 1,
    // { name: "Vice Grip", power: 55 },
    // { name: "Guillotine", power: 100 },
    // { name: "Focus Energy", power: 50 },
    // { name: "Submission", power: 80 },
    move1: 11,
    move2: 12,
    move3: 117,
    move4: 64,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896196/127pinsir_mw4ces.png",
    hp: 65,
  },
  {
    name: "Tauros",
    type: "Normal",
    secondary_type: null,
    weakness: "fairy",
    strength: "ground",
    tier: 2,
    // { name: "Tackle", power: 50 },
    // { name: "Stomp", power: 65 },
    // { name: "Power Whip", power: 120 },
    // { name: "Hyper Beam", power: 150 },
    move1: 32,
    move2: 22,
    move3: 405,
    move4: 61,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/128tauros_ms5ozq.png",
    hp: 75,
  },
  {
    name: "Magikarp",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "rock",
    tier: 1,
    // { name: "Splash", power: 0 },
    // { name: "Tackle", power: 50 },
    // { name: "Flail", power: 1 },
    // { name: "Struggle", power: 50 },
    move1: 150,
    move2: 32,
    move3: 175,
    move4: 165,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896195/129magikarp_ekylji.png",
    hp: 20,
  },
  {
    name: "Gyarados",
    type: "Water",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "rock",
    tier: 3,
    // { name: "Bite", power: 60 },
    // { name: "Dragon Rage", power: 40 },
    // { name: "Hydro Pump", power: 110 },
    // { name: "Hyper Beam", power: 150 },
    move1: 42,
    move2: 80,
    move3: 54,
    move4: 61,
    rarity: "very rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896196/130gyarados_gtodwf.png",
    hp: 95,
  },
  {
    name: "Lapras",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "fire",
    tier: 3,
    // { name: "Water Gun", power: 40 },
    // { name: "Ice Shard", power: 40 },
    // { name: "Body Slam", power: 85 },
    // { name: "Hydro Pump", power: 110 },
    move1: 53,
    move2: 381,
    move3: 33,
    move4: 54,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896196/131lapras_e3lkcw.png",
    hp: 130,
  },
  {
    name: "Ditto",
    type: "Normal",
    secondary_type: null,
    weakness: "ghost",
    strength: "fairy",
    tier: 1,
    // { name: "Transform", power: 0 },
    // { name: "-", power: 0 },
    // { name: "-", power: 0 },
    // { name: "-", power: 0 },
    move1: 144,
    move2: 144,
    move3: 144,
    move4: 144,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896196/132ditto_amaimh.png",
    hp: 48,
  },
  {
    name: "Eevee",
    type: "Normal",
    secondary_type: null,
    weakness: "ghost",
    strength: "fairy",
    tier: 2,
    // { name: "Tackle", power: 40 },
    // { name: "Quick Attack", power: 40 },
    // { name: "Bite", power: 60 },
    // { name: "Swift", power: 60 },
    move1: 32,
    move2: 389,
    move3: 42,
    move4: 129,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896196/133eevee_xs6iuy.png",
    hp: 32,
  },
  {
    name: "Vaporeon",
    type: "Water",
    secondary_type: null,
    weakness: "electric",
    strength: "fire",
    tier: 3,
    // { name: "Water Gun", power: 40 },
    // { name: "Aurora Beam", power: 65 },
    // { name: "Acid Armor", power: 0 },
    // { name: "Hydro Pump", power: 110 },
    move1: 53,
    move2: 60,
    move3: 151,
    move4: 54,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896197/134vaporeon_ry2jxi.png",
    hp: 130,
  },
  {
    name: "Jolteon",
    type: "Electric",
    secondary_type: null,
    weakness: "rock",
    strength: "water",
    tier: 3,
    // { name: "Thunder Shock", power: 40 },
    // { name: "Double Kick", power: 30 },
    // { name: "Pin Missile", power: 25 },
    // { name: "Thunderbolt", power: 90 },
    move1: 391,
    move2: 23,
    move3: 83,
    move4: 243,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896197/135jolteon_nso7ba.png",
    hp: 65,
  },
  {
    name: "Flareon",
    type: "Fire",
    secondary_type: null,
    weakness: "water",
    strength: "grass",
    tier: 3,
    // { name: "Ember", power: 40 },
    // { name: "Quick Attack", power: 40 },
    // { name: "Fire Spin", power: 35 },
    // { name: "Fire Blast", power: 110 },
    move1: 50,
    move2: 389,
    move3: 395,
    move4: 126,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896197/136flareon_sc9gs1.png",
    hp: 65,
  },
  {
    name: "Porygon",
    type: "Normal",
    secondary_type: null,
    weakness: "ghost",
    strength: "fairy",
    tier: 1,
    // { name: "Tackle", power: 50 },
    // { name: "Barrage", power: 15 },
    // { name: "Psybeam", power: 65 },
    // { name: "Tri Attack", power: 80 },
    move1: 32,
    move2: 140,
    move3: 58,
    move4: 161,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896197/137porygon_ur8og1.png",
    hp: 65,
  },
  {
    name: "Omanyte",
    type: "Rock",
    secondary_type: "Water",
    weakness: "psychic",
    strength: "fairy",
    tier: 1,
    // { name: "Constrict", power: 10 },
    // { name: "Bite", power: 60 },
    // { name: "Water Gun", power: 40 },
    // { name: "Hydro Pump", power: 110 },
    move1: 132,
    move2: 42,
    move3: 53,
    move4: 54,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896197/138omanyte_ezn3ma.png",
    hp: 35,
  },
  {
    name: "Omastar",
    type: "Rock",
    secondary_type: "Water",
    weakness: "psychic",
    strength: "fairy",
    tier: 2,
    // { name: "Water Gun", power: 40 },
    // { name: "Hydro Pump", power: 110 },
    // { name: "Spike Cannon", power: 20 },
    // { name: "Rock Slide", power: 75 },
    move1: 53,
    move2: 54,
    move3: 131,
    move4: 157,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896197/139omastar_sakq5o.png",
    hp: 70,
  },
  {
    name: "Kabuto",
    type: "Rock",
    secondary_type: "Water",
    weakness: "psychic",
    strength: "fairy",
    tier: 1,
    // { name: "Scratch", power: 40 },
    // { name: "Poison Sting", power: 15 },
    // { name: "Absorb", power: 20 },
    // { name: "Slash", power: 70 },
    move1: 10,
    move2: 39,
    move3: 69,
    move4: 163,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/140kabuto_pzdlp8.png",
    hp: 30,
  },
  {
    name: "Kabutops",
    type: "Rock",
    secondary_type: "Water",
    weakness: "psychic",
    strength: "fairy",
    tier: 2,
    // { name: "Scratch", power: 40 },
    // { name: "Slash", power: 70 },
    // { name: "Psycho Cut", power: 70 },
    // { name: "Hydro Pump", power: 110 },
    move1: 10,
    move2: 163,
    move3: 186,
    move4: 54,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/141kabutops_yc33hk.png",
    hp: 60,
  },
  {
    name: "Aerodactyl",
    type: "Rock",
    secondary_type: "Flying",
    weakness: "water",
    strength: "ground",
    tier: 3,
    // { name: "Wing Attack", power: 60 },
    // { name: "Aeroblast", power: 100 },
    // { name: "Bite", power: 60 },
    // { name: "Hyper Beam", power: 150 },
    move1: 17,
    move2: 177,
    move3: 42,
    move4: 61,
    rarity: "very rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/142aerodactyl_fjpooj.png",
    hp: 80,
  },
  {
    name: "Snorlax",
    type: "Normal",
    secondary_type: null,
    weakness: "poison",
    strength: "bug",
    tier: 3,
    // { name: "Tackle", power: 50 },
    // { name: "Hyper Beam", power: 150 },
    // { name: "Body Slam", power: 85 },
    // { name: "Submission", power: 80 },
    move1: 32,
    move2: 61,
    move3: 33,
    move4: 64,
    rarity: "rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/143snorlax_aoedmd.png",
    hp: 160,
  },
  {
    name: "Articuno",
    type: "Ice",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "water",
    tier: 3,
    // { name: "Gust", power: 40 },
    // { name: "Ice Beam", power: 90 },
    // { name: "Blizzard", power: 110 },
    // { name: "Aeroblast", power: 177 },
    move1: 16,
    move2: 56,
    move3: 57,
    move4: 177,
    rarity: "very rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/144articuno_dxvgoo.png",
    hp: 90,
  },
  {
    name: "Zapdos",
    type: "Electric",
    secondary_type: "Flying",
    weakness: "rock",
    strength: "water",
    tier: 3,
    // { name: "Thunder", power: 110 },
    // { name: "Thunder Shock", power: 40 },
    // { name: "Drill Peck", power: 80 },
    // { name: "Thunderbolt", power: 90 },
    move1: 252,
    move2: 391,
    move3: 63,
    move4: 243,
    rarity: "very rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/145zapdos_ylomxx.png",
    hp: 90,
  },
  {
    name: "Moltres",
    type: "Fire",
    secondary_type: "Flying",
    weakness: "water",
    strength: "grass",
    tier: 3,
    // { name: "Wing Attack", power: 60 },
    // { name: "Ember", power: 40 },
    // { name: "Aeroblast", power: 100 },
    // { name: "Fire Blast", power: 110 },
    move1: 17,
    move2: 50,
    move3: 177,
    move4: 126,
    rarity: "very rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/146moltres_vlxywq.png",
    hp: 90,
  },
  {
    name: "Dratini",
    type: "Dragon",
    secondary_type: null,
    weakness: "electric",
    strength: "ground",
    tier: 1,
    // { name: "Wrap", power: 15 },
    // { name: "Thunder Fang", power: 65 },
    // { name: "Tackle", power: 40 },
    // { name: "Twister", power: 40 },
    move1: 34,
    move2: 203,
    move3: 32,
    move4: 413,
    rarity: "common",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/147dratini_ugyggt.png",
    hp: 41,
  },
  {
    name: "Dragonair",
    type: "Dragon",
    secondary_type: null,
    weakness: "electric",
    strength: "ground",
    tier: 2,
    // { name: "Slam", power: 80 },
    // { name: "Aeroblast", power: 100 },
    // { name: "Twister", power: 40 },
    // { name: "Dragon Rage", power: 40 },
    move1: 20,
    move2: 177,
    move3: 413,
    move4: 80,
    rarity: "rare",
    evolutionId: 2,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/148dragonair_c8f2td.png",
    hp: 61,
  },
  {
    name: "Dragonite",
    type: "Dragon",
    secondary_type: "Flying",
    weakness: "electric",
    strength: "ground",
    tier: 3,
    // { name: "Dragon Rage", power: 40 },
    // { name: "Draco Meteor", power: 130 },
    // { name: "Aeroblast", power: 100 },
    // { name: "Hyper Beam", power: 150 },
    move1: 80,
    move2: 218,
    move3: 177,
    move4: 61,
    rarity: "very rare",
    evolutionId: 3,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896198/149dragonite_b1vnar.png",
    hp: 91,
  },
  {
    name: "Mewtwo",
    type: "Psychic",
    secondary_type: null,
    weakness: "fairy",
    strength: "ghost",
    tier: 3,
    // { name: "Confusion", power: 50 },
    // { name: "Psywave", power: 130 },
    // { name: "Psychic", power: 90 },
    // { name: "Nightmare", power: 80 },
    move1: 388,
    move2: 140,
    move3: 211,
    move4: 171,
    rarity: "very rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684896178/150mewtwo_nl7c61.png",
    hp: 106,
  },
  {
    name: "Mew",
    type: "Psychic",
    secondary_type: null,
    weakness: "fairy",
    strength: "ghost",
    tier: 3,
    // { name: "Pound", power: 40 },
    // { name: "Mega Punch", power: 80 },
    // { name: "Psywave", power: 130 },
    // { name: "Psychic", power: 90 },
    move1: 1,
    move2: 5,
    move3: 140,
    move4: 211,
    rarity: "very rare",
    evolutionId: 1,
    img_url:
      "https://res.cloudinary.com/duaznt4wg/image/upload/v1684901802/mew-png_jppzde.png",
    hp: 100,
  },
];
